version = 1

test_patterns = ["test_*.py"]

exclude_patterns = ["old_enigma.py"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.10"

[[transformers]]
name = "black"
enabled = true
